# Generated by Django 2.1.1 on 2018-11-07 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['create_time'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
